KAFKA_BOOTSTRAP_SERVERS = "54.226.166.22:9092"

TOPICO_TEMPERATURA = "temperatura"
TOPICO_TEMPERATURA_PROCESSADA = "temperatura_processada"

PROCESSADOR_TAMANHO_BUFFER = 10

SENSOR_INTERVALO_SEGUNDOS = 3
SENSOR_TEMPERATURA_MIN = 20.0
SENSOR_TEMPERATURA_MAX = 35.0

API_BASE_URL = "http://44.223.48.221:8000"
API_CAMINHO_TEMPERATURAS = "/temperaturas"
API_CAMINHO_MEDIA = "/temperaturas/media"

CLIENTE_INTERVALO_SEGUNDOS = 5
CLIENTE_TIMEOUT_SEGUNDOS = 10
